using System;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;

namespace PresetChecker
{
    public class Program
    {
        static Lazy<Settings> _settings = null!;
        static internal Settings settings => _settings.Value;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .SetTypicalOpen(GameRelease.SkyrimSE, "PresetChecker.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .Run(args);
        }

        private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? _state;
        internal static IPatcherState<ISkyrimMod, ISkyrimModGetter> State
        {
            get { return _state!; }
        }
        private static MergeInfo? _mergeInfo;
        private static Textures? _textures;
        private static PresetHandler? _presetHandler;

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            _state = state;
            _mergeInfo = new MergeInfo(settings.InputFolder);
            _textures = new Textures();
            _presetHandler = new PresetHandler(settings.InputFolder, _mergeInfo, _textures);
        }
    }
}
